name: My First CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show system information
        run: |
          echo "CI pipeline is running"
          echo "Hostname:"
          hostname
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -la
